### ISSUE TITLE
Design Volunteer Tshirt

### ISSUE THREAD

**Issue by hannahkane** [mozilla/2015.mozillafestival.org#208] opened 2015-09-18 15:50 UTC
This is a special Tshirt, only given to MozFest volunteers. It should be specific to 2015. 

**Note:** Deadline for this is to be at the printers by October 14

Requirements:
 * Unisex
 * Single color print
 * Should include MozFest logo (cog) + wordmark + "2015"
 * Should include #MozHelp (rather than the word "Volunteer")
 * Could include print on both sides of the shirt

Print specs from the supplier:
 * If it's a full print on the front, it's A3
 * If it's smaller, A4
 * Vector .eps, .pdf, or .ai
 * Should be transparent (no bg color)
 * Writing should be shapes or paths, rather than text

Last year's shirt for references:

![screen shot 2015-09-18 at 8 48 23 am](https://cloud.githubusercontent.com/assets/8389648/9963821/0d874a4a-5de2-11e5-8097-7bdafc2bb960.png)

And the back had "#MozHelp" across the shoulder blades

**Comment by cassiemc** [comment] 2015-09-25 17:13
Do we have a photo of the actual tshirt from last year? cc @marcwalsh @Saallen

**Comment by SpikeUK** [comment] 2015-09-26 06:49
Here is a pic of the t-shirt from 2014 - I have laid the back of one over the front of another
![mozfest14tshirsml](https://cloud.githubusercontent.com/assets/1629474/10116190/1f97b8ae-6423-11e5-935b-54cb145228e1.jpg)

**Comment by cassiemc** [comment] 2015-09-28 13:27
That's really helpful, even unironed :) Thanks @SpikeUK!

@marcwalsh @Saallen @hannahkane We'll need to know what colours the actual t-shirt is available in, and if there are any colour limitations for the printing (we'll stick to flat, one-color).

**Comment by marcwalsh** [comment] 2015-09-28 15:51
@cassiemc - This is the link to the product page. There's lots of options but the most popular choices were orange, red and blue.

http://www.xamax.co.uk/100-gildan-coloured-t-shirt-free-print-offer.html

**Comment by marcwalsh** [comment] 2015-09-29 16:42
@cassiemc just noticed the change in milestone. The deadline for these to go to the printers is Wednesday 14th October and we won't be able to push much further.

**Comment by cassiemc** [comment] 2015-09-29 17:56
Thanks for the clarification @marcwalsh – I had the printing deadlines as October 26 in my head, same as the festival guide. Will revert the milestones.

**Comment by cassiemc** [comment] 2015-09-29 17:57
Actually @marcwalsh can you clarify, is the printer deadline just for the tshirts? Perhaps you could take a gander at our deliverables spreadsheet and note the deadline to the printer in column G? https://docs.google.com/spreadsheets/d/1J4LS4ILtG5x-jxwHEwGuDzXHRHC9IQM4t9fg2OUeRBs/edit#gid=0

**Comment by adiladiladil** [comment] 2015-09-29 18:46
![mozshirt2](https://cloud.githubusercontent.com/assets/11046943/10174632/e5190c1c-66b8-11e5-8d16-6ef9fbd57589.jpg)
![mozshirt1](https://cloud.githubusercontent.com/assets/11046943/10174634/e51fc124-66b8-11e5-9bd8-79e135dc46b1.jpg)
![mozshirt3](https://cloud.githubusercontent.com/assets/11046943/10174633/e51cec74-66b8-11e5-9abf-9121db6f036c.jpg)

**Comment by cassiemc** [comment] 2015-09-29 19:26
I think these basic versions are a good start! Wondering if we can push it a bit more. This is the shirt I showed at today's stand – 
![wordpress-shirt](https://cloud.githubusercontent.com/assets/1186326/10175679/5f8bf11c-66be-11e5-8a46-3cd84e9fc44f.jpg)

We could pull from the iconography on the Mozfest site (and possibly from teach.mozilla.org) to pull off something similar.

**Comment by SpikeUK** [comment] 2015-09-30 06:20
Like the CamelCase 'MozHelp' - nicely mirrors 'MozFest'.
Love the two-colour printing on all three base colour shown but sadly I think we are constrained to single-colour printing by cost.
REALLY love the icon cloud example from @cassiemc  :+1:

**Comment by Saallen** [comment] 2015-09-30 12:13
:heart: The cloud too- it would v cool with all the icons from the spaces on there.

**Comment by cassiemc** [comment] 2015-10-01 15:35
Yes, like the idea of doing it with the space icons, good idea @Saallen!

**Comment by cassiemc** [comment] 2015-10-05 15:02
This is blocked by finalizing the icons. #213

**Comment by adiladiladil** [comment] 2015-10-08 15:20
some options here 
![untitled-2](https://cloud.githubusercontent.com/assets/11046943/10369458/5a5b593a-6da8-11e5-9982-f579dc816f39.jpg)
![untitled-4](https://cloud.githubusercontent.com/assets/11046943/10370069/55f2ee32-6dab-11e5-8790-2cce9632569e.jpg)
![untitled-5](https://cloud.githubusercontent.com/assets/11046943/10370790/8390b2d6-6dae-11e5-947a-b96426a7aef4.jpg)

![mozfest-shirt-1](https://cloud.githubusercontent.com/assets/11046943/10369111/944179ba-6da6-11e5-90d8-3d821043f6ea.jpg)

**Comment by SpikeUK** [comment] 2015-10-08 15:52
Love the randomness of the second option, but like the branding text in the third.

**Comment by cassiemc** [comment] 2015-10-08 16:18
I'm okay with any of these. Cool @adiladil. 
@Saallen is there a verdict on the youth icon?

**Comment by Saallen** [comment] 2015-10-09 13:39
I love the third one but it would be good to match the tote bag so thinking the third one......oooh its hard though they are all awesome

**Comment by cassiemc** [comment] 2015-10-09 13:44
@Saallen We are thinking the third option for the tshirt, since it's serving as memorabilia, and the first or second option for the tote bag, for its timelessness / re-usability. :)

Yes we'll need to update the youth icon on this.

**Comment by adiladiladil** [comment] 2015-10-09 16:30
Here is the update on the shirt with new youth icon
![mozshirt](https://cloud.githubusercontent.com/assets/11046943/10399577/7a6e4e10-6e81-11e5-8803-425484d6bfa9.jpg)

**Comment by cassiemc** [comment] 2015-10-09 16:32
Looks good @adiladil. One thing that just occurred to me – this is two-color. @marcwalsh @Saallen Can you comment on if budget will allow for it?

@adiladil can you do a one-color version as an alt?

**Comment by adiladiladil** [comment] 2015-10-09 16:36
I noticed last years shirts were two color

here are couple 1 color options

![mozshirt2](https://cloud.githubusercontent.com/assets/11046943/10399705/56fef884-6e82-11e5-8013-8364c63b940e.jpg)
![mozshirt3](https://cloud.githubusercontent.com/assets/11046943/10399706/5704ea3c-6e82-11e5-8f7d-c02953d9f8f3.jpg)

**Comment by SpikeUK** [comment] 2015-10-10 02:12
Sorry, no, the 2014 volunteer t-shirts were single-colour printed; yellow on blue t-shirt.

If we are limited to one colour (@marcwalsh ?) I would prefer the pink (fuchsia?) printing rather than the white please.
(So looking forward to getting these :) )

**Comment by marcwalsh** [comment] 2015-10-12 09:32
Two colour is fine @cassiemc @adiladiladil - Will need artwork in vector format today to send to printers please! :)

**Comment by cassiemc** [comment] 2015-10-13 14:04
Excellent, two color it is. @adiladil final artwork?

**Comment by adiladiladil** [comment] 2015-10-13 15:00
@cassiemc @marcwalsh Here are the final files. 2 options for navy blue t shirts and plain white
![mozfest-2015-navy-white-shirt](https://cloud.githubusercontent.com/assets/11046943/10458606/977238a8-7199-11e5-9d10-51aedd89db49.jpg)
![mozfest-2015-shirt-white-shirt](https://cloud.githubusercontent.com/assets/11046943/10458605/976f7b54-7199-11e5-875b-1fdab90e4e73.jpg)


Download Link Here:

http://we.tl/jv3HQkxpWQ

**Comment by cassiemc** [comment] 2015-10-13 15:01
Thanks @adiladil!! Let's go with the navy blue option if possible @marcwalsh

**Comment by cassiemc** [comment] 2015-10-13 15:06
@marcwalsh if you can confirm you have everything you need for this, I'll close this bug :bomb:

**Comment by adiladiladil** [comment] 2015-10-13 15:08
@cassiemc sounds good. @marcwalsh you have both vector files. you can use the one titled Mozfest 2015 Shirt Navy

**Comment by marcwalsh** [comment] 2015-10-13 15:33
Thanks! The bag is blue and it's printed straight on, so I don't need a background on it. Thanks @adiladiladil @cassiemc

**Comment by cassiemc** [comment] 2015-10-13 15:36
@marcwalsh To clarify, this design is for the t-shirt, not the tote bag. Are you able to use the files you have?

**Comment by marcwalsh** [comment] 2015-10-13 16:18
Sorry @cassiemc , yes! I also need the #MozFest for the back with the text outlined as a separate file please.

**Comment by adiladiladil** [comment] 2015-10-13 16:24
Here is the link for the artwork for the back of the Shirts (#MozFest)

we can let the printers know whether we want white or MozFest pink

http://we.tl/d9xu3R4q5h

**Comment by cassiemc** [comment] 2015-10-13 17:04
I think the white works well as per the earlier two-color tshirt design. @adiladil I think you meant to tag @marcwalsh

**Comment by cassiemc** [comment] 2015-10-13 17:12
@marcwalsh if all is good here now, good to close?

**Comment by marcwalsh** [comment] 2015-10-14 11:58
@adiladiladil @cassiemc - Sorry it needs to be #MozHelp not #MozFest, once corrected all good to close!

Thanks!

**Comment by adiladiladil** [comment] 2015-10-14 14:20
@cassiemc @marcwalsh Here is the link to the corrected artwork

http://we.tl/vaG3F0TGj4

**Comment by marcwalsh** [comment] 2015-10-14 15:29
Sorry @adiladiladil could you remove the blue background on the front of the artwork... I'd do it myself but I need to renew my CC subscription. :(

**Comment by adiladiladil** [comment] 2015-10-14 15:33
@marcwalsh here is the update

just let the printers know that the print colors will be white and pink. in the AI file the white is black so they can actually see the artwork

http://we.tl/qFHgk5Xox1

**Comment by marcwalsh** [comment] 2015-10-14 15:35
Will do thanks @adiladiladil 
@cassiemc  - Let's leave this open until it's confirmed okay with printers

**Comment by cassiemc** [comment] 2015-10-22 18:44
@marcwalsh Is this confirmed with printers, can we close?

**Comment by cassiemc** [comment] 2015-10-26 15:16
Assuming this is all good since we're way past the print deadline. Reopen if any issues @marcwalsh!

**Closed by cassiemc** 2015-10-26 15:16 UTC
Labels: Design, P1
