### ISSUE TITLE
Map - Open in map app/ directions tab

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/2015.mozillafestival.org#307] opened 2015-10-26 20:08 UTC
When people tap the map or the point on it they most of times expect to open it in a different app ( Google Maps, Here maps, OSM etc ) or new tab with again some directions ( on google maps etc)

<img src="https://cloud.githubusercontent.com/assets/1391451/10740955/d9e875dc-7c2d-11e5-9e78-a09ee7734e97.jpg" width="300" height="550" />

<img src="https://cloud.githubusercontent.com/assets/1391451/10740935/c3ff9be2-7c2d-11e5-912a-d583c8468c7f.jpg" width="300" height="550" />

**Comment by cassiemc** [comment] 2015-10-26 21:15
This seems like a dupe of https://github.com/mozilla/2015.mozillafestival.org/issues/295. @ioana-chiorean please re-open if it's a different issue!

**Closed by cassiemc** 2015-10-26 21:15 UTC

**Comment by ioana-chiorean** [comment] 2015-10-26 22:13
Added a comment to cover all aspects - but yeah we are pretty covered ( same issue)
