### ISSUE TITLE
Design session & icon banners

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#267] opened 2015-10-15 19:37 UTC
In previous years we have printed our Icons onto fomex a1 boards as part of our wayfinding system to hang from the balconies- Hoping @cassiemc can direct something similar for this year .

**Comment by cassiemc** [comment] 2015-10-15 21:06
Yes totally! What size might be standard for this? Do we have any other specs? (@marcwalsh can you help us with specs and final drop-dead print date?)

**Comment by cassiemc** [comment] 2015-10-20 19:20
Assigning to @natalieworth but still looking for a few details from @marcwalsh or @Saallen

**Comment by Saallen** [comment] 2015-10-20 21:01
@cassie I found these details on an old invoice
750 x 750 mm  on 3mm foamex.
I wonder with Jordans ideas for flags should we make these up on cloth flags of natural colour and hand from the balconies?

**Comment by cassiemc** [comment] 2015-10-21 13:36
I'm not familiar with Jordan's flag idea. @lovegushwa can you fill me in?

I'd assumed we'd stick with the boards so it could be printed at Ravensbourne, we've probably passed our deadline to get assets externally printed at this point. Think this is true @marcwalsh?

**Comment by marcwalsh** [comment] 2015-10-21 14:08
Foamex still has to be printed externally, let me check with a couple of places to see deadlines. Flags is also possible but most likely more expensive. 

How quickly can you turn the designs around. They do not need printer marks etc.

**Comment by cassiemc** [comment] 2015-10-21 14:30
@marcwalsh These should be able to be turned around in a day, right @natalieworth? We just need each of the eight icons and the space names listed here: https://2015.mozillafestival.org/sessions

**Comment by cassiemc** [comment] 2015-10-21 14:46
From @lovegushwa: 
* These hang off rails and can be seen from main congregating areas on Foyer and Speaker floor.
* 1.2 x 2m
* printed on lightweight, nylon fabric
* 2 grommets attached to the top of each banner for hanging

**Comment by cassiemc** [comment] 2015-10-21 15:08
@marcwalsh says this is doable but we should get final print files organized today. @natalieworth @lovegushwa doable? Here is the printer site: https://www.pixartprinting.co.uk/wide-format/printing-banners-mesh/ecoflat-banner/

We need @marcwalsh to help get us h/w measurements for the railings where these will be hung.

**Comment by lauralillepruun** [comment] 2015-10-21 15:11
I will get you the measurements for the railings

**Comment by natalieworth** [comment] 2015-10-21 15:48
Shouldn't take too long to do once the measurements are confirmed. I should be able to do them by this afternoon.

cc @cassiemc @marcwalsh @Saallen

**Comment by lovegushwa** [comment] 2015-10-21 16:42
@cassiemc @marcwalsh @natalieworth @Saallen 
Printing on cloth banner would would look a bit more natural draped over a rail than foamex and is also affordable and available at commercial printers. (there is also fabric printers in the building). 

If you need to hold these up and parade around on the first day (I have seen this in photos on flickr) than foamex is going to work better for that.

<img width="580" alt="screen shot 2015-10-21 at 9 27 19 am" src="https://cloud.githubusercontent.com/assets/12228435/10643107/fa5f6df4-77d5-11e5-9123-a0d4b6ea6d10.png">

**Comment by cassiemc** [comment] 2015-10-21 19:07
@lauralillepruun Any update on the measurements? I'm not sure we'll be able to finalize this today without getting those soon. As soon as we get them I expect a day turnaround for design.

**Comment by cassiemc** [comment] 2015-10-21 19:08
@lovegushwa agree that foamex boards are better for stage parading. @Saallen, do you think we need both boards and flags?

**Comment by lauralillepruun** [comment] 2015-10-21 19:38
@cassiemc sorry,  it is 157cm from the base of the balcony to the railings, but from the floor to the railings its 112cm

**Comment by cassiemc** [comment] 2015-10-21 19:50
@lauralillepruun what about width?

**Comment by lauralillepruun** [comment] 2015-10-21 20:00
@cassiemc I'm not quite sure why you need the width? As you can see from the image above, they run alongside the stairs and across the floors so they will be very wide, but surely we would only be using a small bit of them to attach on to?

**Comment by Saallen** [comment] 2015-10-21 20:13
The choice is yours Jordan, I thought flags could be waved from the stage
and then pinned to the balconies but this applies to boards too. I am not
fussy

**Comment by cassiemc** [comment] 2015-10-21 21:02
@lauralillepruun Just wanted to make sure we didn't run into any pillars. I sort of remember one piece of grating last year being a bit shorter.

I just measured and a comfortable wingspan for me for a bunch of people waving a flag on stage would be between 2 & 3 feet. All the way up to 53 inches. Not sure if that allows for a banner visible from a long distance. cc @lovegushwa @natalieworth

**Comment by natalieworth** [comment] 2015-10-21 21:08
@lauralillepruun Just checking if I have the measurements for the balcony correct? I've eyeballed the size of the banners based on @lovegushwa 's measurements of 1.2m x 2m (although we could reduce the length). I believe this is roughly the size of that unless I've made a mistake in the scaling ratio: 
cc @cassiemc 
![measurements-01](https://cloud.githubusercontent.com/assets/14876567/10650227/1e525d8a-77fd-11e5-8473-aed5b37db11d.png)

**Comment by cassiemc** [comment] 2015-10-21 21:15
@natalieworth @lovegushwa I think we need to go more horizontal than vertical. There will be one banner hung from each floor so we don't want them overlapping.

**Comment by cassiemc** [comment] 2015-10-21 21:20
Also, am okay with whatever @lovegushwa thinks will work!

**Comment by natalieworth** [comment] 2015-10-21 21:22
@cassiemc @lovegushwa Could we do square? I agree it would be good to decrease the length if they are going to be stacked. Are we just doing banners or the foamex boards also?

**Comment by cassiemc** [comment] 2015-10-21 21:23
Need guidance from @Saallen on whether we are doing both but I suspect if we can make just one work for both purposes that'll be better from lots of perspectives (budget, logistics, transport etc)

**Comment by lovegushwa** [comment] 2015-10-21 22:04
@cassiemc @natalieworth We should be able to design visually fist, then workout the size.
(With the constraint that people (or maybe 2 people) should be able to hold these) 

My feeling is that If it's possible to print fabric these will look more professional (banners have been hung off rails forever, and they look festive, can have great material qualities with light) If not, let's do foam board. @marcwalsh can your printer do fabric banners?

Here is .AI that can be hacked on:

<img width="1079" alt="screen shot 2015-10-21 at 2 52 51 pm" src="https://cloud.githubusercontent.com/assets/12228435/10651266/74dd64d2-7803-11e5-8bbb-b156208610f3.png">

Banners I used at a previous conference:
<img width="584" alt="screen shot 2015-10-21 at 3 00 46 pm" src="https://cloud.githubusercontent.com/assets/12228435/10651465/8d832494-7804-11e5-84cb-df343f52718c.png">

**Comment by cassiemc** [comment] 2015-10-21 22:17
@lovegushwa these look great as long as they aren't too tall for a short person to hold up over their head. Here's the printer site again for reference: ttps://www.pixartprinting.co.uk/wide-format/printing-banners-mesh/ecoflat-banner/

**Comment by natalieworth** [comment] 2015-10-22 16:39
@lovegushwa I can prep the type/ icons and some design for this, then just copy them over to the final banner size. Do we have confirmed dimensions yet? Thanks
cc @cassiemc @Saallen @lauralillepruun

**Comment by marcwalsh** [comment] 2015-10-22 16:53
@cassiemc @lovegushwa  There's a couple of options:

Banner - More PVC like material:
https://www.pixartprinting.co.uk/wide-format/printing-banners-mesh/ecoflat-banner/

There is synthectic material:
https://www.pixartprinting.co.uk/printing-flags-textiles/flags/

And printing on cotton:
https://www.pixartprinting.co.uk/printing-flags-textiles/natural-fabrics/

Totally depends on the look you're going for! :)

**Comment by lauralillepruun** [comment] 2015-10-22 17:19
@natalieworth the 157cm is from the top of the balcony to the bottom of the floor 
<img width="272" alt="screen shot 2015-10-22 at 1 18 57 pm" src="https://cloud.githubusercontent.com/assets/15231997/10672668/7bf41240-78bf-11e5-8e84-66644c1db02c.png">

**Comment by lauralillepruun** [comment] 2015-10-22 17:20
As in outside of the balcony

**Comment by lovegushwa** [comment] 2015-10-22 18:34
@natalieworth @lauralillepruun @cassiemc 
See the measurements below. I maximized the size based on what a person (or two people) can hold and peak over the top. The pendant part (in pink) can very in length depending how @natalieworth want's trim it. A person holding this would allow that to drape on the floor. It's critical that the type go now lower than ~110cm from the top edge so "science" for example, is not on the ground when some one holds these.

<img width="1058" alt="screen shot 2015-10-22 at 11 25 25 am" src="https://cloud.githubusercontent.com/assets/12228435/10674468/dbae86c6-78af-11e5-9ec7-3f002620dcea.png">

**Comment by natalieworth** [comment] 2015-10-22 18:38
These are some quick iterations for colour/type. I'm going to have to adjust the placement based on the new measurements and I'll make sure the type is at a comfortable eye level if someone is holding these up. https://redpen.io/ow32b4ea63d4b0f7cc

**Comment by natalieworth** [comment] 2015-10-22 19:59
@cassiemc First banner drafts are up on red pen with @lovegushwa 's dimensions: https://redpen.io/ywaadd47cafaf603ec

**Comment by lovegushwa** [comment] 2015-10-22 20:59
@cassiemc @natalieworth 

Natalie and I just talked. Let’s go with gradients. She is going to look at an additional graphic touch so these really pop. We will play the gradient’s off the main stage colors (Stage design design should be up for review later today so we can make final color decisions on these banners tomorrow morning and ship.)

**Comment by lovegushwa** [comment] 2015-10-26 00:37
@marcwalsh can your order these banners? 1 of each, 8 total.

Press ready artwork:
https://drive.google.com/folderview?id=0B2qu3ExKWIlvMktjdWFWMkZiTGM&usp=sharing

Exact specifications:
https://www.pixartprinting.co.uk/printing-flags-textiles/flags/
<img width="885" alt="screen shot 2015-10-25 at 5 31 38 pm" src="https://cloud.githubusercontent.com/assets/12228435/10719074/7122b19c-7b3e-11e5-9805-394de4ab5f40.png">

CC @cassiemc

**Comment by cassiemc** [comment] 2015-10-26 14:42
@marcwalsh let us know if you need anything else, otherwise we can close the issue.

**Comment by cassiemc** [comment] 2015-10-26 14:46
@lovegushwa @natalieworth We noticed the bottom of the banner is just a lighter color, not necessarily a line set up to be cut... Are you planning to cut these yourself? Otherwise might need to set up a proper bleed for the printer.

**Comment by marcwalsh** [comment] 2015-10-26 14:58
@lovegushwa @natalieworth - Just checked with the printers and this item doesn't allow for cutting to a shape, which would mean that you have to cut them onsite.

We would have to go for something more rigid if we wanted to cut it to the shape you want.

**Comment by lovegushwa** [comment] 2015-10-26 15:21
We will cut these, fabric sheers will work since its nylon cloth. I'm more
comfortable with this than the other available materials. The lighter color
is the cut line.

**Comment by marcwalsh** [comment] 2015-10-26 20:46
@lovegushwa - Ordered!

**Comment by lovegushwa** [comment] 2015-10-26 20:50
yes! thank you @marcwalsh

**Closed by lovegushwa** 2015-10-26 20:50 UTC
Labels: Design, P1, wayfinding

**Comment by cassiemc** [comment] 2015-10-26 21:22
high fives all around!!!

**Comment by natalieworth** [comment] 2015-10-26 21:23
Woot woot

**Comment by lovegushwa** [comment] 2015-10-26 22:06
:+1: !
