### ISSUE TITLE
Link to "MozFest website" on attendee's ticket email points to 2014 website

### ISSUE THREAD

**Issue by SpikeUK** [mozilla/2015.mozillafestival.org#337] opened 2015-11-03 10:44 UTC
Issue reported by an attendee. The receipt email has a link to "MozFest website" in the text. This points to the 2014 webpage ie http://2014.mozillafestival.org  - please see screengrab.
![screenshot_20151103-093901](https://cloud.githubusercontent.com/assets/1629474/10906240/c88e655e-8217-11e5-9557-21c04445225f.png)

**Comment by hannahkane** [comment] 2015-11-04 14:43
Yikes. Not sure what to do about this now, since we can't retroactively fix emails. Should we send a follow-up email to everyone who has a ticket with the correct link? @Saallen ?

**Comment by Saallen** [comment] 2015-11-04 14:50
Hey- I had a look at this and the issue is only on the youth ticket on the follow up message when folks buy a ticket- and from the amount of emails I am getting about the youth ticket I don't think many folks are reading this so not too concerned

**Comment by hannahkane** [comment] 2015-11-04 14:52
OK, closing unless otherwise advised.

**Closed by hannahkane** 2015-11-04 14:52 UTC
