### ISSUE TITLE
Small content updates for the website-

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#331] opened 2015-10-31 20:03 UTC
There are some minor content updates required on the website - many have been captured on other issues but not updated so thought I should make a new issue for them all so they are easier to manage and update
- [ ] Contact info on guidelines page #197 
- [x]  Twitter handles on Global Village bios Jon Rogers - @ileddigital
 Ian Forresters- @cubicgarden and Jasmine Cox - @wearesorryfor 

cc @mmmavis @hannahkane @ioana-chiorean @thornet

**Comment by ioana-chiorean** [comment] 2015-10-31 20:28
I can take care of them @Saallen - I just need a confirmation on #197 on the new texts ( for ex the text propose has no phone etc)

**Comment by ioana-chiorean** [comment] 2015-10-31 20:36
Second part is covered in PR #332

**Comment by hannahkane** [comment] 2015-11-04 16:36
I'm going to close this because now this is just a dupe of #197

**Closed by hannahkane** 2015-11-04 16:36 UTC
Labels: 2015 Site, Content, enhancement
