### ISSUE TITLE
Design visuals for mainstage video screens when stage is unoccupied.

### ISSUE THREAD

**Issue by HPaulJohnson** [mozilla/2015.mozillafestival.org#290] opened 2015-10-23 17:10 UTC
We'd like some rolling video/slides for the main video screens to be shown when stage is unoccupied throughout the day. Some initial ideas of content include: https://docs.google.com/document/d/1L-iwk5IxrDaU3mI75HGCeGwNqbx4TgwXyb3WMeYhJWo/edit

cc: @natalieworth @lovegushwa

**Comment by edrushka** [comment] 2015-10-23 20:13
adding myself

**Comment by lovegushwa** [comment] 2015-10-28 16:54
![img_20151023_112714 1](https://cloud.githubusercontent.com/assets/12228435/10795956/4be2bc02-7d59-11e5-8125-50b5c09ba864.jpg)
@natalieworth another classically horrible sketch. 

What we need to get started:
Still 1: Straight up Mozfest logo
Still 2: Animated version of the poster (use the Mozfont)
Still 3: Photo or video roll  ( @HPaulJohnson direction here? )
Still 4: small hashtag based messages

**Comment by cassiemc** [comment] 2015-10-28 20:57
@HPaulJohnson We need some specs for this. What is the size and resolution, and what type of final video file do you need? cc @natalieworth

**Comment by natalieworth** [comment] 2015-10-28 21:23
@lovegushwa When you get a chance, could you link me to the file downloads for Adil's typeface if they're available?

**Comment by HPaulJohnson** [comment] 2015-10-28 21:44
@marcwalsh @Saallen do you know the answer to @cassiemc question about screen size and resolution?

RE: photo vs. video roll, let's go with photos - we have more to work with starting out and it will be easier to incorporate real time updates as appropriate.

**Comment by marcwalsh** [comment] 2015-10-29 14:16
The screens are HD so make sure it's 1920x1080 (square pixels). For video, they are normally played off a Mac Mini, so a H264 video would be fine!

I can always convert them if necessary while testing.

**Comment by lovegushwa** [comment] 2015-10-29 17:51
@natalieworth some of the backdrop design process might be helpful for transitions / background.
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvYUNDeE1yaUN0UE0/view?usp=sharing

<img width="761" alt="screen shot 2015-10-28 at 2 24 59 pm" src="https://cloud.githubusercontent.com/assets/12228435/10803526/d9832a44-7d7f-11e5-8425-f1f482e95325.png">
<img width="758" alt="screen shot 2015-10-28 at 2 24 52 pm" src="https://cloud.githubusercontent.com/assets/12228435/10803529/dcc91330-7d7f-11e5-8bd6-eb3c68c95b19.png">
<img width="755" alt="screen shot 2015-10-28 at 2 24 40 pm" src="https://cloud.githubusercontent.com/assets/12228435/10803535/df4e828e-7d7f-11e5-9879-ff8739a40a93.png">
<img width="758" alt="screen shot 2015-10-28 at 2 24 05 pm" src="https://cloud.githubusercontent.com/assets/12228435/10803537/e32b7132-7d7f-11e5-90ec-1958d3a50b68.png">
<img width="759" alt="screen shot 2015-10-28 at 2 23 55 pm" src="https://cloud.githubusercontent.com/assets/12228435/10803539/e59afd20-7d7f-11e5-972d-145deb648484.png">
<img width="756" alt="screen shot 2015-10-28 at 2 22 08 pm" src="https://cloud.githubusercontent.com/assets/12228435/10803543/eadd0698-7d7f-11e5-851a-d7b83867e6ce.png">
<img width="762" alt="screen shot 2015-10-28 at 2 21 58 pm" src="https://cloud.githubusercontent.com/assets/12228435/10803575/1aa657bc-7d80-11e5-9259-821e2d3113c0.png">
<img width="758" alt="screen shot 2015-10-28 at 2 21 52 pm" src="https://cloud.githubusercontent.com/assets/12228435/10803576/1ab509c4-7d80-11e5-93f9-9a14242cfcd0.png">

**Comment by natalieworth** [comment] 2015-10-29 18:01
@HPaulJohnson Do we want to include a gear store promo too in the video? I noticed we're promoting a couple other Mozilla related products, or if we should just stick to firefox 42 and teach.mozilla.org.

**Comment by HPaulJohnson** [comment] 2015-10-29 18:14
@natalieworth - great idea, yes. 

also, would like to add in some information about the "fireside" chats, one on Saturday afternoon with Jacob from Souktel and one on Sunday with Mitchell. Want to make sure those get promoted and are well attended. @KevZawacki can you provide details for natalie to include on screen (chat titles, time and location and participants)

**Comment by cassiemc** [comment] 2015-10-29 19:20
@HPaulJohnson can you post the content you want included here?

**Comment by HPaulJohnson** [comment] 2015-10-29 20:34
This is the initial list of content: 
https://docs.google.com/document/d/1L-iwk5IxrDaU3mI75HGCeGwNqbx4TgwXyb3WMeYhJWo/edit

 I'll work on copy for the ones that require it.

**Comment by natalieworth** [comment] 2015-10-29 22:20
@HPaulJohnson Are there any visuals that are required for the promotions, or can I do what I think is best?

**Comment by HPaulJohnson** [comment] 2015-10-29 22:27
@natalieworth you can do what you think works best. the exception will be the FF 42 promo which I'm tracking down some assets for and hope to have something to send to you today to work with.

**Comment by HPaulJohnson** [comment] 2015-10-29 23:53
Draft copy for a bunch of the slides now available: https://docs.google.com/document/d/1L-iwk5IxrDaU3mI75HGCeGwNqbx4TgwXyb3WMeYhJWo/edit

**Comment by KevZawacki** [comment] 2015-10-30 13:44
@HPaulJohnson Still need a hand with fireside chat copy?

From your doc: the title, time and participants for the Saturday chat is right on. Not sure about the location -- floor 4 is correct?

The Sunday chat still needs development, so we can't commit all the copy yet. But, it will definitely be Mitchell at 1 p.m.

**Comment by natalieworth** [comment] 2015-10-31 00:57
@cassiemc @lovegushwa @HPaulJohnson Slides are up on redpen with a few comments/ questions: https://redpen.io/ko597921be06e6bad9

I'll upload/ link to some animation transitions once the style frames are good to go. Thanks!

**Comment by natalieworth** [comment] 2015-11-02 21:38
Hey @HPaulJohnson were you able to get the assets for the FF42 promo?

**Comment by lovegushwa** [comment] 2015-11-02 22:03
@HPaulJohnson when you get a chance check out @natalieworth repen we need to trim down some of these longer slides.
https://redpen.io/ko597921be06e6bad9

**Comment by lovegushwa** [comment] 2015-11-02 22:39
@natalieworth can your post or send a link to video transitions :)?

**Comment by natalieworth** [comment] 2015-11-02 22:47
@HPaulJohnson @lovegushwa @edrushka I just posted some updates to the slide template based on your feedback:https://redpen.io/qy71f00b290e5dcbf0 I'm also exporting some subtle animation for the video. I'll upload to google doc and post on here soon. Thanks

**Comment by natalieworth** [comment] 2015-11-03 00:45
@lovegushwa I've also put some rough .mov samples up of the suble animation on google drive: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0R1hBUmUxaUctR1E

Just waiting on confirmed copy and then I can add the remainder of the frames

**Comment by natalieworth** [comment] 2015-11-03 00:48
Hey Jordan, here's the link:
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0R1hBUmUxaUctR1E

On Mon, Nov 2, 2015 at 2:39 PM, lovegushwa <notifications@github.com> wrote:

> @natalieworth <https://github.com/natalieworth> can your post or send a
> link to video transitions :)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/2015.mozillafestival.org/issues/290#issuecomment-153180530>
> .
>



-- 
Graphic Design Intern, Vancouver
natalie@mozillafoundation.org

**Comment by edrushka** [comment] 2015-11-03 10:20
I really love the animation. This looks fantastic.

**Comment by HPaulJohnson** [comment] 2015-11-03 10:21
+1 - animation looks awesome. will work on finalizing copy today.

**Comment by HPaulJohnson** [comment] 2015-11-03 12:10
@natalieworth would it be possible to get a .jpg of the #mozfest image from the redpen, sized to 1400 x 1120 pixels, for use on our Medium publication?

**Comment by marcwalsh** [comment] 2015-11-03 13:00
Also, @natalieworth am I able to get the source file for this so we're able to make some other specific screens for lunch, coffee, wifi etc.

**Comment by marcwalsh** [comment] 2015-11-03 13:01
The above might also be for @lovegushwa I'm looking for the source file for this:

https://redpen.io/qy71f00b290e5dcbf0

**Comment by HPaulJohnson** [comment] 2015-11-03 14:39
Everything looks good. I think we can drop Maker Party. 

@natalieworth I sent you some assets for FF42 slide so take a look and let me know if there's anything there that works. We can drop that one too if it doesn't work. 

For 'lingo demystifyer' I think we need to see it animated to make sure it works, then we can build out the variations, along with the poster variations. 

Next step would be to see a near final animation with all completed slides + some community photos to see how it looks. Do you have everything you need for photos?

**Comment by chrislarry33** [comment] 2015-11-03 14:57
cool just ping me

**Comment by marcwalsh** [comment] 2015-11-04 13:03
@natalieworth / @lovegushwa - I really need the slides for the screens by 3 or 4PM GMT please

**Comment by natalieworth** [comment] 2015-11-04 18:36
@marcwalsh Here's a link to the video tile .ai files: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0QVFYX0Q3VldoRG8

I don't have confirmed assets/ design for the FF42 tile. Let me know if you need anything else. Thanks

**Comment by natalieworth** [comment] 2015-11-05 01:37
@HPaulJohnson Would something like this work for the FF42 slide:
![mozfest_styletiles_08-12](https://github-cloud.s3.amazonaws.com/assets%2F14876567%2F10957597%2Fc30d510e-831a-11e5-9ef2-01ae9300821c.png)

**Comment by natalieworth** [comment] 2015-11-05 01:40
@HPaulJohnson Let me know too if there is any approved copy that we could use.

@lovegushwa I've also put the most recent .mov file up (version 5): https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0ckd1cGxIZml0ekU/view

All that's left to add are the lingo words and the FF42 slide. Let me know if the transitions are better now? :D
Thanks!

**Comment by HPaulJohnson** [comment] 2015-11-05 09:46
@natalieworth - this is so awesome!! thank you. 

Question about the Firefox slide come from a the spreadsheet of campaign assets I forwarded? I just want to make sure this is approved campaign language before I say yes. I can run by the brand team also to make sure, just let me know the original source. 

Otherwise, I love it and just have a few small edits/comments:
* There's a single photo included. Is the idea to include more, or more as we go? The single photo feels weird and if we are including we'll want to make sure we have lots of diversity included. 
* For Gear Store, can we add: "Use promo code MOZFEST and get 15% off through Nov 15, 2015."
* For session slide, we can use shortlink, mzl.la/sessions and use the copy "find the schedule here"
* For Jacob and Ben's fireside slide, the title is now "The Mobile Web and Social Good"
* For the conversations with Medium slide, the title is "The inclusive Web, leading in the open, and networked learning and local action"
* For Mitchell's fireside slide, the title is now "The Web Ahead"

**Comment by natalieworth** [comment] 2015-11-05 16:52
Hi @HPaulJohnson Thanks for the feedback and I'll make the changes and post asap. I'm going to be adding additional images too, I was just using a few as place holder.

**Comment by natalieworth** [comment] 2015-11-05 20:42
Just updated the content/ slides on the google drive (Version 6): https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0R1hBUmUxaUctR1E&usp=drive_web&ddrp=1#

cc @lovegushwa @HPaulJohnson @cassiemc

**Comment by cassiemc** [comment] 2015-11-06 15:31
URGENT
Hey @natalieworth We can't open version 6, any chance you can reupload by 5:45GMT (9:45am PT)? I know it's cutting it close!

**Comment by natalieworth** [comment] 2015-11-06 16:35
Hey @cassiemc , for sure! Just got to the office and I'll reupload asap. @HPaulJohnson Did you want me to add in the FF42 promo quickly too? Thanks

**Comment by cassiemc** [comment] 2015-11-06 16:38
Great THANK you @natalieworth! Could you do two versions, one with and one without? @HPaulJohnson is busy on the floor at the moment.

**Comment by natalieworth** [comment] 2015-11-06 16:39
Yes, I'll upload the one without first right now to the google drive. Almost done exporting

**Comment by natalieworth** [comment] 2015-11-06 16:56
@cassiemc Here's the version 6 exported again: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0UDZnVlp1NEUtMkU

Just working on adding the FF42 and I'll upload another version to the drive, thanks

**Comment by natalieworth** [comment] 2015-11-06 18:03
Second video (uploading) with the Firefox slide and the definition section added: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0UDZnVlp1NEUtMkU&usp=drive_web&ddrp=1# Thanks! Just ping/ email me if you need any quick changes. I'll also be around late tonight/ tomorrow morning if there are any last minute changes that you guys need before Saturday.

@HPaulJohnson @cassiemc @lovegushwa

**Comment by cassiemc** [comment] 2015-11-06 18:48
@natalieworth Thank you, the quick changes are much appreciated. 

Unfortunately we had a caching problem with the schedule app so we had to change the URL – we'll have to update the video again! New link should be: http://mzl.la/schedule

cc @marcwalsh Not sure if you had other screens with the schedule app url that will need to be updated.

**Comment by cassiemc** [comment] 2015-11-06 18:53
Nix that @natalieworth! Your shortlink was fine, we were able to update where the link pointed to. No need to update the link.

We DO though need to remove the slide promoting the Fireside chat with Mitchell Baker.

@HPaulJohnson says to drop the FF42 slide as well, since we would probably need to show it around here before displaying it, and there's not much time.

Thanks @natalieworth!

**Comment by natalieworth** [comment] 2015-11-06 19:51
@cassiemc Updated video is uploaded on teh google drive (version 3) with the slides removed https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0UDZnVlp1NEUtMkU

**Comment by natalieworth** [comment] 2015-11-09 16:59
@cassiemc Closing all of my MozFest tickets! :D

**Comment by natalieworth** [comment] 2015-11-09 17:01
@cassiemc Closing all of my MozFest tickets! :D

**Closed by natalieworth** 2015-11-09 17:01 UTC
Labels: P1, wayfinding
